name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        #php: [7.4, 7.3, 7.2]
        php: [7.4]
        #laravel: [8.*, 7.*, 6.*, "5.8.*", "5.7.*"]
        laravel: [8.*]
        dependency-version: [prefer-lowest, prefer-stable]
        os: [ubuntu-latest]
        exclude:
            - laravel: 5.7.*
              php: 7.4
            - laravel: 5.8.*
              php: 7.4

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-${{ matrix.dependency-version }}-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: |
          composer global require laravel/installer
          cd ~
          composer create-project laravel/laravel="${{ matrix.laravel }}" testproject
          cd ~/testproject
          composer require laravel/dusk

      - name: Install Dusk Components
        run: |
          cd ~/testproject
          php artisan dusk:install

      - name: Install package
        run: |
          cd ~/testproject
          composer require paksuco/dusk-time-travel

      - name: Execute tests
        run: |
          cd ~/testproject
          php artisan dusk /vendor/paksuco/dusk-time-travel/tests/Browser/ExtensionTest.php
